src/PlatformBundle/Entity/Image.php
<?php

namespace PlatformBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks
 */
class Image {

    /**
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(name="url", type="string", length=255)
     */
    private $url;

    /**
     * @ORM\Column(name="alt", type="string", length=255)
     */
    private $alt;

    /**
     * @var UploadedFile
     * @Assert\File(
     *     maxSize = "1024k",
     *     mimeTypes = {"image/png"},
     *     mimeTypesMessage = "Veuillez selectionner un fichier valide."
     * )
     */
    private $file;
    // On ajoute cet attribut pour y stocker le nom du fichier temporairement
    private $tempFilename;

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload() {
        // Si jamais il n'y a pas de fichier (champ facultatif), on ne fait rien
        if (null === $this->file) {
            return;
        }
        // Le nom du fichier est son id, on doit juste stocker également son extension
        // Pour faire propre, on devrait renommer cet attribut en « extension », plutôt que « url »
        $this->url = $this->file->guessExtension();
        // Et on génère l'attribut alt de la balise <img>, à la valeur du nom du fichier sur le PC de l'internaute
        $this->alt = $this->file->getClientOriginalName();
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload() {
        // Si jamais il n'y a pas de fichier (champ facultatif), on ne fait rien
        if (null === $this->file) {
            return;
        }
        // Si on avait un ancien fichier (attribut tempFilename non null), on le supprime
        if (null !== $this->tempFilename) {
            $oldFile = $this->getUploadRootDir() . '/' . $this->id . '.' . $this->tempFilename;
            if (file_exists($oldFile)) {
                unlink($oldFile);
            }
        }
        // On déplace le fichier envoyé dans le répertoire de notre choix
        $this->file->move(
                $this->getUploadRootDir(), // Le répertoire de destination
                $this->id . '.' . $this->url   // Le nom du fichier à créer, ici « id.extension »
        );
    }

    /**
     * @ORM\PreRemove()
     */
    public function preRemoveUpload() {
        // On sauvegarde temporairement le nom du fichier, car il dépend de l'id
        $this->tempFilename = $this->getUploadRootDir() . '/' . $this->id . '.' . $this->url;
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeUpload() {
        // En PostRemove, on n'a pas accès à l'id, on utilise notre nom sauvegardé
        if (file_exists($this->tempFilename)) {
            // On supprime le fichier
            unlink($this->tempFilename);
        }
    }

    public function getUploadDir() {
        // On retourne le chemin relatif vers l'image pour un navigateur (relatif au répertoire /web donc)
        return 'uploads/img';
    }

    protected function getUploadRootDir() {
        // On retourne le chemin relatif vers l'image pour notre code PHP
        return __DIR__ . '/../../../web/' . $this->getUploadDir();
    }

    public function getWebPath() {
        return $this->getUploadDir() . '/' . $this->getId() . '.' . $this->getUrl();
    }

    /**
     * @return int
     */
    public function getId() {
        return $this->id;
    }

    /**
     * @param string $url
     */
    public function setUrl($url) {
        $this->url = $url;
    }

    /**
     * @return string
     */
    public function getUrl() {
        return $this->url;
    }

    /**
     * @param string $alt
     */
    public function setAlt($alt) {
        $this->alt = $alt;
    }

    /**
     * @return string
     */
    public function getAlt() {
        return $this->alt;
    }

    /**
     * @return UploadedFile
     */
    public function getFile() {
        return $this->file;
    }

    /**
     * @param UploadedFile $file
     */
    // On modifie le setter de File, pour prendre en compte l'upload d'un fichier lorsqu'il en existe déjà un autre
    public function setFile(UploadedFile $file) {
        $this->file = $file;
        // On vérifie si on avait déjà un fichier pour cette entité
        if (null !== $this->url) {
            // On sauvegarde l'extension du fichier pour le supprimer plus tard
            $this->tempFilename = $this->url;
            // On réinitialise les valeurs des attributs url et alt
            $this->url = null;
            $this->alt = null;
        }
    }

}

src/PlatformBundle/Controller/FrontController.php
<?php

namespace PlatformBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use PlatformBundle\Entity\Cours;
use PlatformBundle\Entity\Image;
use PlatformBundle\Entity\User;
use PlatformBundle\Form\Type\CoursRdvType;
use PlatformBundle\Form\Type\RechercheCours;
use PlatformBundle\Form\Type\CoursPratiqueType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

class FrontController extends Controller {

    public function indexAction(Request $request) {
        return $this->render('PlatformBundle:Front:index.html.twig');
    }

    public function listecoursAction(Request $request) {
        $service = $this->get('platform.cours');

        $listecours = $service->rechercheCours();
        $form = $this->createForm(RechercheCours::class);
        $form->handleRequest($request);
        if ($request->isMethod('POST') && $form->isSubmitted()) {
            $listecours = $service->rechercheCoursPratique($form->getData()['pratique']);
        }

        $paginator = $this->get('knp_paginator');
        $pagination = $paginator->paginate(
                $listecours, $request->query->getInt('page', 1), 5
        );

        return $this->render('PlatformBundle:Front:listecours.html.twig', array('pagination' => $pagination, 'form' => $form->createView()));
    }

    public function coursAction(Cours $cours) {
        $service = $this->get('platform.cours');
        if ($this->get('security.authorization_checker')->isGranted('ROLE_ELEVE')) {
            $eleveInscrit = $service->eleveInscrit($cours, $this->getUser());
        } else {
            $eleveInscrit = null;
        }
        $nbEleve = $service->nbEleve($cours);
        $listEleve = $service->eleveCours($cours);
        return $this->render('PlatformBundle:Front:cours.html.twig', array(
                    'cours' => $cours,
                    'nbEleve' => $nbEleve,
                    'eleveInscrit' => $eleveInscrit,
                    'listEleve' => $listEleve)
        );
    }

    /**
     * @Security("has_role('ROLE_PROF') or has_role('ROLE_ELEVE') or has_role('ROLE_ADMIN')")
     */
    public function infoAction(Request $request) {
        return $this->render('PlatformBundle:Front:info.html.twig');
    }

    /**
     * @Security("has_role('ROLE_ELEVE')")
     */
    public function registercoursAction(Cours $cours) {
        $service = $this->get('platform.cours');

        $service->registerCours($this->getUser(), $cours);
        $nbEleve = $service->nbEleve($cours);
        $eleveInscrit = $service->eleveInscrit($cours, $this->getUser());
        return $this->render('PlatformBundle:Front:cours.html.twig', array(
                    'cours' => $cours,
                    'nbEleve' => $nbEleve,
                    'eleveInscrit' => $eleveInscrit));
    }

    /**
     * @Security("has_role('ROLE_ELEVE')")
     */
    public function coursinscritAction(Request $request) {
        $service = $this->get('platform.cours');
        $listecours = $service->rechercheCoursInscrit($this->getUser());

        $paginator = $this->get('knp_paginator');
        $pagination = $paginator->paginate(
                $listecours, $request->query->getInt('page', 1), 5
        );

        return $this->render('PlatformBundle:Front:coursinscrit.html.twig', array('pagination' => $pagination));
    }

    /**
     * @Security("has_role('ROLE_ELEVE')")
     */
    public function deletecoursAction(Request $request, Cours $cours) {
        $service = $this->get('platform.cours');
        $service->deleteCoursInscrit($this->getUser(), $cours);
        $listecours = $service->rechercheCoursInscrit($this->getUser());

        $paginator = $this->get('knp_paginator');
        $pagination = $paginator->paginate(
                $listecours, $request->query->getInt('page', 1), 5
        );

        return $this->render('PlatformBundle:Front:coursinscrit.html.twig', array('pagination' => $pagination));
    }

    /**
     * @Security("has_role('ROLE_PROF')")
     */
    public function coursprofAction(Request $request) {
        return $this->render('PlatformBundle:Front:coursprof.html.twig');
    }

    /**
     * @Security("has_role('ROLE_PROF')")
     */
    public function addcoursrdvAction(Request $request) {
        $service = $this->get('platform.cours');
        $form = $this->createForm(CoursRdvType::class);
        $form->handleRequest($request);
        if ($request->isMethod('POST') && $form->isSubmitted() && $form->isValid()) {
            /** @var User $user */
            $cours = $form->getData();
            $cours->setUser($this->getUser());
            $service->addCoursRdv($cours);

            return $this->redirectToRoute('bp_addcoursrdv');
        }
        return $this->render('PlatformBundle:Front:addcoursrdv.html.twig', [
                    'form' => $form->createView()
        ]);
    }

    /**
     * @Security("has_role('ROLE_PROF')")
     */
    public function addcourspratiqueAction(Request $request) {
        $service = $this->get('platform.cours');
        $form = $this->createForm(CoursPratiqueType::class);
        $form->handleRequest($request);
        if ($request->isMethod('POST') && $form->isSubmitted() && $form->isValid()) {
            /** @var User $user */
            $cours = $form->getData();
            $cours->setUser($this->getUser());
            $service->addCoursPratique($cours);

            return $this->redirectToRoute('bp_addcourspratique');
        }
        return $this->render('PlatformBundle:Front:addcourspratique.html.twig', [
                    'form' => $form->createView()
        ]);
    }

    /**
     * @Security("has_role('ROLE_PROF')")
     */
    public function courscreeAction(Request $request) {
        $service = $this->get('platform.cours');
        $listecours = $service->rechercheCoursCree($this->getUser());

        $paginator = $this->get('knp_paginator');
        $pagination = $paginator->paginate(
                $listecours, $request->query->getInt('page', 1), 5
        );

        return $this->render('PlatformBundle:Front:courscree.html.twig', array('pagination' => $pagination));
    }

    /**
     * @Security("has_role('ROLE_PROF')")
     */
    public function editcoursrdvAction(Request $request, Cours $cours) {
        if ($this->getUser() != $cours->getUser()) {
            throw $this->createAccessDeniedException('Impossible d\'acceder à cette page.');
        }
        $service = $this->get('platform.cours');
        $form = $this->createForm(CoursRdvType::class, $cours);
        $form->handleRequest($request);
        if ($request->isMethod('POST') && $form->isSubmitted() && $form->isValid()) {
            /** @var User $user */
            $cours = $form->getData();
            $service->editCours($cours);

            return $this->redirectToRoute('bp_editcoursrdv', array(
                        'id' => $cours->getId()));
        }
        return $this->render('PlatformBundle:Front:editcoursrdv.html.twig', [
                    'form' => $form->createView()
        ]);
    }

    /**
     * @Security("has_role('ROLE_PROF')")
     */
    public function editcourspratiqueAction(Request $request, Cours $cours) {
        if ($this->getUser() != $cours->getUser()) {
            throw $this->createAccessDeniedException('Impossible d\'acceder à cette page.');
        }
        $service = $this->get('platform.cours');
        $form = $this->createForm(CoursPratiqueType::class, $cours);
        $form->handleRequest($request);
        if ($request->isMethod('POST') && $form->isSubmitted() && $form->isValid()) {
            /** @var User $user */
            $cours = $form->getData();
            $service->editCours($cours);

            return $this->redirectToRoute('bp_editcourspratique', array(
                        'id' => $cours->getId()));
        }
        return $this->render('PlatformBundle:Front:editcourspratique.html.twig', [
                    'form' => $form->createView()
        ]);
    }

    /**
     * @Security("has_role('ROLE_PROF')")
     */
    public function removecoursAction(Request $request, Cours $cours) {
        if ($this->getUser() != $cours->getUser()) {
            throw $this->createAccessDeniedException('Impossible d\'acceder à cette page.');
        }
        $service = $this->get('platform.cours');

        $service->removeCours($cours);
        $listecours = $service->rechercheCoursCree($this->getUser());

        $paginator = $this->get('knp_paginator');
        $pagination = $paginator->paginate(
                $listecours, $request->query->getInt('page', 1), 5
        );

        return $this->render('PlatformBundle:Front:courscree.html.twig', array('pagination' => $pagination));
    }

}

src/PlatformBundle/Resources/views/Front/cours.html.twig
{% extends "PlatformBundle::layout.html.twig" %}

{% block title %}Cours - {{ parent() }}{% endblock %}

{% block body %}
    <div class="container">
        <br>
        {% for message in app.flashes('success') %}
            <div class="alert alert-success">
                {{ message }}
            </div>
        {% endfor %}
        {% for message in app.flashes('warning') %}
            <div class="alert alert-warning">
                {{ message }}
            </div>
        {% endfor %}
        {% for message in app.flashes('info') %}
            <div class="alert alert-info">
                {{ message }}
            </div>
        {% endfor %}
        <div class="bg-faded p-4 my-4 row">
            <div class="col-md-2">
                {% if cours.user.image is not null %}
                    <img
                        src="{{ asset(cours.user.image.webPath) }}"
                        alt="{{ cours.user.image.alt }}"
                        height="120"
                        width="100"
                        />
                {% else %}
                    <img
                        src="{{ asset("uploads/img/default.png") }}"
                        alt="image par default"
                        height="120"
                        width="100"
                        />
                {% endif %}
            </div>
            <div class="col-md-10">
                <strong>Titre du cours : </strong>{{ cours.titre }}<br>
                <strong>Auteur : </strong>{{ cours.user.nom }} {{ cours.user.prenom }} 
                {% if is_granted(['ROLE_PROF','ROLE_ELEVE','ROLE_ADMIN']) %}
                    <a href="{{ path('contact', {'id': cours.user.id} ) }}">Contactez-moi</a>
                {% endif %}<br>
                <strong>Date de réunion : </strong>{% if cours.datereunion is not null %} {{ cours.datereunion|date('d/m/Y H:i') }} {% else %} Non renseigné {% endif %}<br>
                <strong>Lieu de réunion : </strong>
                {% if cours.adressereunion is not null %} {{ cours.adressereunion }}{% else %} Non renseigné {% endif %},
                {% if cours.villereunion is not null %} {{ cours.villereunion }} {% else %} Non renseigné {% endif %},
                {% if cours.codepostalreunion is not null %} {{ cours.codepostalreunion }} {% else %} Non renseigné {% endif %}<br>
                <strong>Nombre d'élèves inscrit : </strong>
                {% if cours.elevemax is not null %} {{ nbEleve }}/{{ cours.elevemax }} {% else %} Non renseigné {% endif %}
            </div>
            {% if is_granted(['ROLE_PROF','ROLE_ELEVE','ROLE_ADMIN']) %}
                <a href="{{ path('signalement', {'id': cours.id} ) }}" class="pull-right">Signaler le cours</a>
            {% endif %}
            <div class="bg-light p-2 my-2 border border-dark col-md-12">              
                {{ cours.contenue|raw }}
            </div>
            {% if not is_granted(['ROLE_PROF','ROLE_ELEVE']) %}
                <p><a href="{{ path('security_login') }}"><strong>Connectez-vous pour vous inscrire à ce cours !</strong></a></p>
            {% elseif is_granted('ROLE_ELEVE') %}
                {% if cours.elevemax > 0 %}
                    {% if eleveInscrit >= 1 %}
                        <p><a href="{{ path('bp_deletecours', {'id': cours.id} ) }}" onclick="return confirm('Etes-vous sur ?')"><strong>Se désinscrire de ce cours !</strong></a></p>
                    {% else %}
                        {% if nbEleve >= cours.elevemax %}
                            <p><strong>Ce cours est complet.</strong></p>
                        {% else %}
                            <p><a href="{{ path('bp_registercours', {'id': cours.id} ) }}"><strong>S'inscrire à ce cours !</strong></a></p>
                        {% endif %}
                    {% endif %}
                {% endif %}
            {% endif %}  
        </div>
        {% if is_granted('ROLE_PROF') and cours.pratique == 0 and app.user == cours.user %}
            <div class="bg-faded p-4 my-4">
                <hr class="divider">
                <h2 class="text-center text-lg text-uppercase my-0">
                    <strong>Elève(s) inscrit</strong>
                </h2>
                <hr class="divider">
                {% if listEleve is not empty %}
                    <div class="table-responsive">
                        <table class="table table-hover table-striped">
                            <thead>
                                <tr>
                                    <th>Nom</th>
                                    <th>Prénom</th>
                                    <th>Email</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for eleve in listEleve %}
                                    <tr>
                                        <td>{{ eleve.user.nom }}</td>
                                        <td>{{ eleve.user.prenom }}</td>
                                        <td><a href="{{ path('contact', {'id': eleve.user.id} ) }}">Contacter</a></td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                {% else %}
                    <p>Pas d'élève inscrit.</p>
                {% endif %}
            </div>
        {% endif %}
    </div>
    <!-- /.container -->

{% endblock %}

src/PlatformBundle/Resources/views/Front/coursinscrit.html.twig
{% extends "PlatformBundle::layout.html.twig" %}

{% block title %}Cours inscrit - {{ parent() }}{% endblock %}

{% block body %}
    <div class="container">

        <div class="bg-faded p-4 my-4">
            {% for message in app.flashes('success') %}
                <div class="alert alert-success">
                    {{ message }}
                </div>
            {% endfor %}
            <hr class="divider">
            <h2 class="text-center text-lg text-uppercase my-0">Voici
                <strong> les cours inscrit</strong>
            </h2>
            <hr class="divider">
            {% if pagination is not empty %}
                <p>
                    {% for coursinscrit in pagination %}
                        <a href="{{ path('bp_platform_cours', {'id': coursinscrit.cours.id}) }}" class="nounderline" >
                            <li>
                                <div class="bg-light p-2 my-2 border border-dark row">
                                    <div class="col-md-2">
                                        {% if coursinscrit.cours.user.image is not null %}
                                            <img
                                                src="{{ asset(coursinscrit.cours.user.image.webPath) }}"
                                                alt="{{ coursinscrit.cours.user.image.alt }}"
                                                height="120"
                                                width="100"
                                                />
                                        {% else %}
                                            <img
                                                src="{{ asset("uploads/img/default.png") }}"
                                                alt="image par default"
                                                height="120"
                                                width="100"
                                                />
                                        {% endif %}
                                    </div>
                                    <div class="col-md-10">
                                        <strong>Titre du cours : </strong>{{ coursinscrit.cours.titre }}<br>
                                        <strong>Auteur : </strong>{{ coursinscrit.cours.user.nom }} {{ coursinscrit.cours.user.prenom }}<br>
                                        <strong>Date de réunion : </strong>{% if coursinscrit.cours.datereunion is not null %} {{ coursinscrit.cours.datereunion|date('d/m/Y H:i') }} {% else %} Non renseigné {% endif %}<br>
                                        <strong>Lieu de réunion : </strong>
                                        {% if coursinscrit.cours.adressereunion is not null %} {{ coursinscrit.cours.adressereunion }}{% else %} Non renseigné {% endif %},
                                        {% if coursinscrit.cours.villereunion is not null %} {{ coursinscrit.cours.villereunion }} {% else %} Non renseigné {% endif %},
                                        {% if coursinscrit.cours.codepostalreunion is not null %} {{ coursinscrit.cours.codepostalreunion }} {% else %} Non renseigné {% endif %}<br>
                                        <strong>Nombre d'élèves max. : </strong>
                                        {% if coursinscrit.cours.elevemax is not null %} {{ coursinscrit.cours.elevemax }} {% else %} Non renseigné {% endif %}
                                    </div>
                                </div>
                            </li>
                        </a>
                    {% endfor %}
                </p>
                <div class="navigation">
                    {{ knp_pagination_render(pagination) }}
                </div>
            {% else %}
                <p><strong>Vous n'êtes inscrit à aucun cours.</strong></p>
            {% endif %}
        </div>
    </div>
    <!-- /.container -->
{% endblock %}

src/PlatformBundle/Resources/views/Front/info.html.twig
{% extends "PlatformBundle::layout.html.twig" %}

{% block title %}Information perso - {{ parent() }}{% endblock %}

{% block body %}
    <div class="container">
        <div class="bg-faded p-4 my-4">
            <hr class="divider">
            <h2 class="text-center text-lg text-uppercase my-0">
                <strong>Mes informations</strong>
            </h2>
            <hr class="divider">
            {% for message in app.flashes('notice') %}
                <div class="alert alert-success">
                    {{ message }}
                </div>
            {% endfor %}
            <div class="bg-faded p-4 my-4 row">
                <div class="col-md-3">
                    {% if app.user.image is not null %}
                        <img
                            src="{{ asset(app.user.image.webPath) }}"
                            alt="{{ app.user.image.alt }}"
                            height="210"
                            width="140"
                            />
                    {% else %}
                        <img
                            src="{{ asset("uploads/img/default.png") }}"
                            alt="image par default"
                            height="210"
                            width="140"
                            />
                    {% endif %}
                </div>
                <div class="col-md-9">
                    <p>
                        <strong>Email</strong> : {{ app.user.email }}
                        <br>
                        <strong>Mot de passe</strong> : ********
                        <br>
                        <strong>Nom</strong> : {% if app.user.nom is not null %} {{ app.user.nom }} {% else %} Non renseigné {% endif %}
                        <br>
                        <strong>Prénom</strong> : {% if app.user.prenom is not null %} {{ app.user.prenom }} {% else %} Non renseigné {% endif %}
                        <br>
                        <strong>Adresse</strong> : {% if app.user.adresse is not null %} {{ app.user.adresse }} {% else %} Non renseigné {% endif %}
                        <br>
                        <strong>Ville</strong> : {% if app.user.ville is not null %} {{ app.user.ville }} {% else %} Non renseigné {% endif %}
                        <br>
                        <strong>Code Postal</strong> : {% if app.user.codepostal is not null %} {{ app.user.codepostal }} {% else %} Non renseigné {% endif %}
                        <br>
                        <strong>Présentation</strong> :<br>
                        {% if app.user.presentation is null %} Pas de présentation {% else %} {{ app.user.presentation }} {% endif %}
                    </p>
                </div>
            </div>
            <a class="btn btn-outline-primary btn-lg" href="{{ path('bp_edituser') }}" role="button">Modifier votre profil</a>
            <br><br>
            <a class="btn btn-outline-primary btn-lg" href="{{ path('bp_editmdp') }}" role="button">Modifier votre mot de passe</a>
            <a class="btn btn-outline-primary btn-lg" href="{{ path('bp_editmail') }}" role="button">Modifier adresse mail</a>
        </div>
    </div>
    <!-- /.container -->
{% endblock %}

src/PlatformBundle/Resources/views/Front/listecours.html.twig
{% extends "PlatformBundle::layout.html.twig" %}

{% block title %}Cours - {{ parent() }}{% endblock %}

{% block body %}
    <div class="container">

        <div class="bg-faded p-4 my-4">
            <hr class="divider">
            <h2 class="text-center text-lg text-uppercase my-0">Voici
                <strong> les cours proposés</strong>
            </h2>
            <hr class="divider">

            {% if pagination is not empty %}
                {{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}

                {{ form_errors(form) }}

                <div class="form-group row">
                    <strong>{{ form_label(form.pratique, "Afficher les cours : ", {'label_attr': {'class': 'col-sm-12 control-label'}}) }}</strong>
                    <div class="alert-warning">
                        {{ form_errors(form.pratique) }}
                    </div>
                    <div class="col-sm-10">
                        {{ form_widget(form.pratique) }}
                    </div>
                    <button type="submit" class="btn btn-primary" formnovalidate>Recherche</button>
                </div>

                {{ form_rest(form) }}

                {{ form_end(form) }}
                <p>
                    {% for cours in pagination %}
                        <a href="{{ path('bp_platform_cours', {'id': cours.id}) }}" class="nounderline" >
                            <li>
                                <div class="bg-light p-2 my-2 border border-dark row">
                                    <div class="col-md-2">
                                        {% if cours.user.image is not null %}
                                            <img
                                                src="{{ asset(cours.user.image.webPath) }}"
                                                alt="{{ cours.user.image.alt }}"
                                                height="120"
                                                width="100"
                                                />
                                        {% else %}
                                            <img
                                                src="{{ asset("uploads/img/default.png") }}"
                                                alt="image par default"
                                                height="120"
                                                width="100"
                                                />
                                        {% endif %}
                                    </div>
                                    <div class="col-md-10">
                                        <strong>Titre du cours : </strong>{{ cours.titre }}<br>
                                        <strong>Auteur : </strong>{{ cours.user.nom }} {{ cours.user.prenom }}<br>
                                        {% if cours.pratique == 0 %}
                                            <strong>Date de réunion : </strong>{% if cours.datereunion is not null %} {{ cours.datereunion|date('d/m/Y H:i') }} {% else %} Non renseigné {% endif %}<br>
                                            <strong>Lieu de réunion : </strong>
                                            {% if cours.adressereunion is not null %} {{ cours.adressereunion }}{% else %} Non renseigné {% endif %},
                                            {% if cours.villereunion is not null %} {{ cours.villereunion }} {% else %} Non renseigné {% endif %},
                                            {% if cours.codepostalreunion is not null %} {{ cours.codepostalreunion }} {% else %} Non renseigné {% endif %}<br>
                                            <strong>Nombre d'élèves max. : </strong>
                                            {% if cours.elevemax is not null %} {{ cours.elevemax }} {% else %} Non renseigné {% endif %}
                                        {% endif %}
                                    </div>
                                </div>
                            </li>
                        </a>
                    {% endfor %}
                </p>
                <div class="navigation">
                    {{ knp_pagination_render(pagination) }}
                </div>
            {% else %}
                <p><strong>Il n'y a aucun cours pour le moment.</strong></p>
            {% endif %}
        </div>
    </div>
    <!-- /.container -->
{% endblock %}